# Generated by Django 4.2.2 on 2023-08-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calen.ward')),
            ],
        ),
    ]
