# Generated by Django 4.2.2 on 2023-08-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poweroutage',
            name='ward',
        ),
        migrations.AddField(
            model_name='poweroutage',
            name='ward_number',
            field=models.PositiveIntegerField(default=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
